version: '3'
services:
  postgres-db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=bloggingapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=subhajit123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network


  blogging-app:
    container_name: blogging-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6060:6060
    networks:
      - app-network
    depends_on:
      - postgres-db

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local