spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bloggingapp
    username: postgres
    password: subhajit123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: /api
  port: 6060

app:
  jwt:
    secret: dsfhdsfhdsufudsfhuidshfidshfucdf
    expiration: 360000 # 1 hour
