spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bloggingapp
    username: postgres
    password: subhajit123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api
  port: 6060